### ISSUE TITLE
Allow inlining top-level constants

### ISSUE THREAD

**Issue by lazarljubenovic** [fabiosantoscode/terser#101]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V`)**

`terser 3.8.1`

**Complete CLI command or `minify()` options used**

```text
terser --compress --mangle toplevel --toplevel --ecma 8 -- file.js
```

**`terser` input**

```js
const x = 1

function fn () {
  switch (x) {
    case 1: return 10
    case 2: return 20
    case 3: return 30
  }
}

console.log(fn())
```

**`terser` output or error**

```js
const c=1;console.log(function(){switch(c){case 1:return 10;case 2:return 20;case 3:return 30}}());
```

**Expected result**

Not sure if this is a bug really or not. Without logging the result of the function, the output is an empty string (because of `--toplevel`), so with calling it I would expect it to inline the `x` (renamed to `c`), especially since it's called only ONCE.

If it's a constant, nothing can change it -- and since `--toplevel` is on, it means that I don't care for the `c` existing there. So shouldn't it work the same way the code below works?

```js
// in
function fn () {
  const x = 1
  switch (x) {
    case 1: return 10
    case 2: return 20
    case 3: return 30
  }
}

console.log(fn())

// out
console.log(10);
```

**Comment by lazarljubenovic** [comment]
@kzc Thanks! So I guess it's expected, then?

**Comment by kzc** [comment]
Working as designed/documented.

**Comment by kzc** [comment]
Set `passes` to 999999 if you want. The point at which the AST doesn't simplify, it will give up - often at around 6 passes or so, depending on the size and complexity of the code.

The "when to stop simplifying" issue is not unique to this compiler. It's a speed versus output size tradeoff. `passes` is set to 1 by default because in most cases it doesn't improve minification size by more than a fraction of a percent. Each pass takes additional CPU time and yields rapidly diminishing returns. The user can decide what settings work best for their given project.

This issue can be closed.
