### ISSUE TITLE
Dedup object properties

### ISSUE THREAD

**Issue by eight04** [fabiosantoscode/terser#108]
**Bug report or Feature request?**

Feature request.

**Version (complete output of `terser -V`)**

terser@3.8.2

**`terser` input**

```js
const {minify} = require("terser");
const source = `
const module = {exports: {}};
module.exports = () => "foo";
defineModule(module);
`;
minify(source, {toplevel: true, compress: {passes: 3}}).code;

```
[REPL](https://repl.it/@eight041/terser-dedup-prop)

**`terser` output or error**
```js
defineModule({exports:{},exports:()=>"foo"});
```

**Expected result**
```js
defineModule({exports:()=>"foo"});
```

Terser can drop the first `exports` in this case.

**Comment by kzc** [comment]
> Terser can drop the first exports in this case.

While true for consecutive duplicate properties without side effects, it's not a valid optimization in general. This optimization was considered in the past for uglify but was not implemented because of the complexity involved. Consider:
```
$ echo 'console.log(JSON.stringify({a: console.log("side effect"), a: 2}));' | node
side effect
{"a":2}

$ echo 'console.log(JSON.stringify({a: 2}));' | node
{"a":2}
```
and
```
$ echo 'console.log(JSON.stringify({x: 1, y: 2, x: 3}));' | node
{"x":3,"y":2}

$ echo 'console.log(JSON.stringify({y: 2, x: 3}));' | node
{"y":2,"x":3}
```
and duplicate properties are not valid on older JS engines in strict mode:
```
$ echo '"use strict"; console.log(JSON.stringify({x: 1, y: 2, x: 3}));' | node0_12_9 
[stdin]:1
"use strict"; console.log(JSON.stringify({x: 1, y: 2, x: 3}));
                                                      ^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
```
There are probably more corner cases that I haven't considered.

This would be a rare optimization opportunity and would not significantly impact the size of the vast majority of minified code. Every new feature slows down minification ever so slightly and can potentially introduce bugs, so the risk/reward ratio has to be favorable to be worth implementing.

**Comment by fabiosantoscode** [comment]
I agree with @kzc. But thanks for the suggestion anyway @eight04

**Comment by eight04** [comment]
For @kzc 's examples, we can optimize it from:
```js
console.log(JSON.stringify({a: console.log("side effect"), a: 2}));
console.log(JSON.stringify({x: 1, y: 2, x: 3}));
```
to:
```js
console.log(JSON.stringify({a: (console.log("side effect"), 2)}));
console.log(JSON.stringify({x: (1, 3), y: 2}));
```
We only have to concern if the value that is moved has side effects and the expression between two props have side effects too. For example:
```js
console.log({
  a: foo,
  b: console.log("bar"),
  a: console.log("baz") // this can't be merged into the previous `a`.
                        // the previous `a` is *unused* though.
});
```
But note that terser doesn't inline property when it has side effects:
```js
const {minify} = require("terser");
const source = `
const foo = {
  a: 123,
  b: console.log("b")
};
foo.a = console.log("a2");
console.log(foo);
`;
console.log(minify(source, {toplevel: true, compress: {passes: 4}}).code);
```
Result:
```js
const o={a:123,b:console.log("b")};o.a=console.log("a2"),console.log(o);
```
[REPL](https://repl.it/@eight041/terser-dedup-prop-1)
So we can assume that the value is pure (unless the duplicated property is produced by other tools).

> This would be a rare optimization opportunity

I don't think it's that rare.

1. You can see this pattern when a library provides a default config object (or JSON), and the user wants to overwrite some properties:
    ```js
    import config from "some-config";
    config.foo = "foo";
    config.bar = "bar";
    ```
    After bundled and compressed by terser:
    ```js
    const o = {foo:"default value defined in some-config",bar:"...",...,foo:"foo",bar:"bar"};...
    ```
    The `foo` and `bar` are duplicated.
2. When the bundler generates some module wrapper just like the example I posted.

> would not significantly impact the size of the vast majority of minified code.

It depends. The larger the default value is, the more characters are dropped.

> Every new feature slows down minification 

I have no knowledge about terser's codebase so I can't disagree with that, but this optimization only takes place when duplicated property exists.

----

Off topic. Rollup might be able to drop these unused defaults in the future:
https://github.com/rollup/rollup/issues/2201

**Comment by kzc** [comment]
> You can see this pattern when a library provides a default config object (or JSON), and the user wants to overwrite some properties

Sounds like a niche case. In a large bundle it probably wouldn't be noticeable after gzip.

In the grand scheme of things, although users think code transforms are significant in minification, the majority of the space savings comes from [whitespace elimination and symbol name mangling](https://github.com/fabiosantoscode/terser#terser-fast-minify-mode). Users value correctness and stability and get annoyed when new optimizations are introduced that take several releases to get right. So the implementation risk to reward ratio has to be worth it.

> but this optimization only takes place when duplicated property exists

Even the act of making that determination takes CPU cycles. It could involve O(n*log(n)) complexity in the best case for each object literal. Since the use of object literals is widespread in ecmascript code it'd likely impact minify speed.

Object literals are modelled as follows:

```
$ echo '({a:1, b:2, a:3, 4:0})' | terser -o ast
{
  "_class": "AST_Toplevel",
  "body": [
    {
      "_class": "AST_SimpleStatement",
      "body": {
        "_class": "AST_Object",
        "properties": [
          {
            "_class": "AST_ObjectKeyVal",
            "key": "a",
            "value": {
              "_class": "AST_Number",
              "value": 1
            }
          },
          {
            "_class": "AST_ObjectKeyVal",
            "key": "b",
            "value": {
              "_class": "AST_Number",
              "value": 2
            }
          },
          {
            "_class": "AST_ObjectKeyVal",
            "key": "a",
            "value": {
              "_class": "AST_Number",
              "value": 3
            }
          },
          {
            "_class": "AST_ObjectKeyVal",
            "key": "4",
            "value": {
              "_class": "AST_Number",
              "value": 0
            }
          }
        ]
      }
    }
  ]
}
```

The key/value pairs are modelled as an array rather than a map to preserve side effect order. 

If this proposed optimization were to be implemented behind a new compress option and would only act on side-effect-free object literals without ES6+ constructs (such as computed properties, object spread and shorthand methods) it could be viable. The logic involved in dealing with intra object literal side effects is not worth the hassle.

@eight04 If you want to put together a PR with comprehensive tests we'd be happy to review and consider it. The PR would have to demonstrate no speed and size regressions in [`test/benchmark.js`](https://github.com/fabiosantoscode/terser/blob/master/test/benchmark.js) and some multi-megabyte bundles if the proposed compress option is to be enabled by default.

> Rollup might be able to drop these unused defaults in the future

That'd be great. Less work for us. :-)

**Comment by fabiosantoscode** [comment]
There's already mechanisms in place to determine whether an expression has side effects.

**Comment by fabiosantoscode** [comment]
I think if you keep a hash of object keys while you parse the object, you could easily detect duplicates and mark them as such immediately.

**Comment by kzc** [comment]
The logic would belong in compress.js rather than parse.js, as the input AST could be derived from acorn/mozilla AST. Also, ASTs change as they are transformed by the compressor:
```
$ echo 'var o = {a:1, b:2}; o.a = 3; console.log(o);' | terser -mc
var o={a:1,b:2,a:3};console.log(o);
```
Anything's doable, but as with any optimization, would have to verify whether it significantly slows down general minification of large inputs.

**Comment by fabiosantoscode** [comment]
Got it, makes sense.
