### ISSUE TITLE
Browser usage

### ISSUE THREAD

**Issue by fabiosantoscode** [fabiosantoscode/terser#31]
**Bug report or feature request?**

Remove `eval` calls to enable uglifyJS to be used in the browser.

**master**

PR's welcome!

**Comment by kzc** [comment]
`eval` can be used in the browser.

To make a browser friendly version run from the CLI with the `--self` option. See `test/mocha/cli.js` and `test/mocha/spidermonkey.js` for examples.

**Comment by fabiosantoscode** [comment]
But shouldn't we expose a browserifiable module like other packages? I feel uglify isn't used in the browser much but when it is, it shouldn't be so complicated :/ there's even a package for that on npm.

**Comment by kzc** [comment]
Methods on AST classes are added via an `eval` mechanism. You're talking about a major code change that would prevent any possibility of future upstream merges with `uglify-js`.

**Comment by kzc** [comment]
> Methods on AST classes are added via an `eval` mechanism.

Correction - `eval` is not used. The `Function` constructor is used to the same effect for `DEFNODE` and `DEFMETHOD`:

https://github.com/fabiosantoscode/terser/blob/68f76f4c8592a4b9095b2baaa7f177641f916f95/lib/ast.js#L46-L88

If traditional prototype methods were to be used then the structure of the code would change considerably:

https://github.com/fabiosantoscode/terser/blob/68f76f4c8592a4b9095b2baaa7f177641f916f95/lib/compress.js#L2230-L2257

**Comment by kzc** [comment]
If a way is devised to replace the following:

https://github.com/fabiosantoscode/terser/blob/master/lib/ast.js#L61

with a deterministic non-`eval` equivalent without significant performance degradation then that at the very least it would improve debugging of this project. Half the existing stack frames currently display "eval" as result of this `Function` constructor. If such a change could be implemented then the structure of AST code would remain the same.

**Comment by fabiosantoscode** [comment]
I don't think building the constructors there would be a problem.

The problem is exactly those require statements, I think. Changing only that shouldn't have much impact on mergeability. And if it's not just that, I'll give up (and maybe use the package.json "browser" field to give browser users a --self build as you said)

**Comment by fabiosantoscode** [comment]
Hmm. That's used with a fs.readFileSync and concatenated which is how we can access all variables between files without require. That's not browserifiable. I think the "browser" field will have to do.

**Comment by goto-bus-stop** [comment]
yeah, `terser --self --wrap exports` generates a nice CommonJS module. i think that'd be great to include in the npm package by default :)

That prebuilt version could also just be used as the `main` file in Node by default actually

**Comment by Flamefire** [comment]
Have a look at https://github.com/mishoo/UglifyJS2/pull/3183

**Comment by kzc** [comment]
@Flamefire That's quite interesting - particularly the speed up.

If the PR is ported to Terser and passes all tests on supported Node versions (not presently the case) we may consider it. Briefly looking at it I don't think the `--self` stuff would work - it'd have to produce code without any `require`()s. Also, the PR should use Uglify code formatting conventions - see `CONTRIBUTING.md`.

I'd like to wait and see whether `uglify-js` adopts this PR which would ease porting of upstream bug fixes to Terser. It's not necessarily a show-stopper, just something to be considered.

Side note - I'm not crazy about all the AST class aliases in each file, but I understand why it was done. Would the timings worsen if they were in the form `AST.Class` rather than `AST_Class`?

**Comment by Flamefire** [comment]
TBH I have no idea where it comes from. I assume node loading files via `require` is faster than eval

There are even tests for `--self` and those pass (failure is due to linux file casing -.-), I invented a little `require` hack to make `--self` work. It is not universal but it works for this case, e.g. it requires the file reading to be in the right order.   
Please feel free to point me to things where I did not adhere to the code formatting. I tried to copy the style around and am not sure what I missed.

As mentioned in the PR I'd rather use AST.Class. I'd expect the performance impact to be negligible.

**Comment by Flamefire** [comment]
Tests pass

**Comment by kzc** [comment]
@Flamefire Discussion from https://github.com/mishoo/UglifyJS2/pull/3183 continued here as this pertains to `terser` rather than `uglify-js`...

Thanks for putting together this PR, but I'm not crazy about the generated code in [commit 1](https://github.com/mishoo/UglifyJS2/pull/3183/commits/1ce651ee147cde15ce2921d3a3b13e3abb25bc1f) for `--self` with the require replacement:

```js
$ bin/uglifyjs --self -b | grep require
    function require(filename) {
        return require[getVarNameFromPath(filename)];
    var exports = require["__utils_exports"] = {};
    var exports = require["__ast_exports"] = {};
    var utils = require("./utils");
    var exports = require["__parse_exports"] = {};
    var utils = require("./utils");
    var ast = require("./ast");
    var exports = require["__scope_exports"] = {};
    var utils = require("./utils");
    var ast = require("./ast");
    var parse = require("./parse");
    var exports = require["__output_exports"] = {};
    var utils = require("./utils");
    var ast = require("./ast");
    var parse = require("./parse");
        var requireSemicolonChars = makePredicate("( [ + * / - , .");
                    if (options.semicolons || requireSemicolonChars[ch]) {
    var exports = require["__compress_exports"] = {};
    var utils = require("./utils");
    var ast = require("./ast");
    var parse = require("./parse");
    var OutputStream = require("./output").OutputStream;
    require("./scope");
    var exports = require["__sourcemap_exports"] = {};
    var MOZ_SourceMap = require("source-map");
    var utils = require("./utils");
    var exports = require["__mozilla_ast_exports"] = {};
    var ast = require("./ast");
    var exports = require["__propmangle_exports"] = {};
    var utils = require("./utils");
    var scope = require("./scope");
    var ast = require("./ast");
    var exports = require["__minify_exports"] = {};
    var utils = require("./utils");
    var ast = require("./ast");
    var parse = require("./parse");
    var OutputStream = require("./output").OutputStream;
    var Compressor = require("./compress").Compressor;
    var SourceMap = require("./sourcemap").SourceMap;
    var propmangle = require("./propmangle");
```

The `--self` handling in `master` is simple and self-contained and doesn't make reference to `require` or bundling equivalent. The only external dependency needed in `--self` in `master` is to the optional source map module, `MOZ_SourceMap`, which may be passed in the IIFE as a parameter and is not needed in a browser.

I am not comfortable with the redundant AST class alias declarations in every local source file in order to avoid the speed slowdown associated with `AST.ClassName`. I don't know if there's a way to both avoid the redundant declarations and not slow down the code with `AST.ClassName` without either putting all the code in a single file or having an additional transpile step using something like Rollup, which I'd like to avoid as it'd slow down the iterative code change and test process.

And as much as `terser` is an independent fork of `uglify-js`, there is an advantage to keeping the code structure as similar as possible to the upstream project to facilitate cherry-picking future fixes.

**Comment by fabiosantoscode** [comment]
I'm happy to drop --self if it comes to it. Besides browser usage (and today you're hard-pressed to find a project which is not using a bundler, as much as a project that needs to minify in the clientside), and a self-minify test (which we could still do with a devDependency of webpack, parcel or browserify), what good is it for?

**Comment by Flamefire** [comment]
UglifyJS worked by pasting all files into one big eval. The modularized version uses require and exports.

Hence the old `--self` could simply copy everything together but with the require you have to make sure it returns the correct exports object especially to allow the common `importName.className` syntax. In UglifyJS code this is like 3 simple lines of code which are very simple (that was my goal as opposed to a full-blown solution like browserify) and in the generated code it does not matter much. So I don't think this is more complicated than the original code.

Yeah the slowdown for `AST.ClassName` bothers me to. That would have been the pretty solution I wanted... The kinda redundant section at the beginning is the price you'd have to pay. But it is also declaring an intent like "This module is using these other ones"   
Yes I would also avoid any additional step if that affects development.

To keep the code structure the same I'd go with the var-imports at the top of the file. Maybe put it in a region and fold it.

About `--self`: I'd still provide a browser-version. Although it does not have to be `--self` but maybe browserify. One might also use it to pretty-print code in the browser or some other JS-Engine that is not based on node. But yes the self-minify-test is not important.   
Anyway: What is the problem with my solution? 3 lines of code (the generated does not count) and it works well.

**Comment by fabiosantoscode** [comment]
> I'd still provide a browser-version.

I think that if we use require() and exports, the browser version will be the same as the node version.

**Comment by Flamefire** [comment]
Unfortunately not:

> Browsers don't have the require method defined, but Node.js does. With Browserify you can write code that uses require in the same way that you would use it in Node.
(http://browserify.org/)

**Comment by kzc** [comment]
Now that `AST.ClassName` use throughout the code base has proven to slow down minification, the only other option is to have dozens of redundant class aliases in every source file. All this just for the sake of using a debugger in an IDE?

The current code base is elegant, lean and mean and runs on all JS engines going back 5 years. No unnecessary dependencies, no transpilation, and minimal redundant code.  Incorporating a bundler into the release is not something I'd support. The success of an open source project depends not only on what new features are incorporated, but more importantly what features are rejected in order to maintain quality and keep the scope of the project focused.

**Comment by goto-bus-stop** [comment]
@Flamefire i think the point is that, if uglify uses commonjs, then people could bundle it with browserify in their own apps.

does the speed up from using CJS also happen if you use the `--self` bundle from Node? it could be built in a prepublish step and the package.json `main` field set to point to the `--self` bundle if it's much faster. As a fork of uglify-js it seems best for porting efforts to keep it mostly the same.

**Comment by Martii** [comment]
Not sure if this will help and it's throwing those willing to investigate...

Re:

> Browsers don't have the require method defined, but Node.js does. With Browserify you can write code that uses require in the same way that you would use it in Node.
(http://browserify.org/)

Sort of... however I've seen a shim in a .user.js, which confused me at first, but it worked at that time.

See also:
* https://www.npmjs.com/package/brunch
* https://github.com/rslifka/fate_of_all_fools/issues/37#issuecomment-356732391

**Comment by Flamefire** [comment]
@kzc Well actually that is my point: The success from OS projects depends on the people participating or how hard it is to do so. How do you add new features or fix bugs? For me it takes multiple cycles of following the code flow with a debugger to figure out what is even happening. After knowing what is happening I can then figure out what goes wrong and where. I then set a breakpoint there and run it with multiple inputs and/or multiple times while changing stuff to have the intermediate result match the expected.   
With this eval-stuff this is not possible/quite hard as you loose all your breakpoints and you have to search the evaled code every time to set it again. This is amplified by the missing modularization so that most tests run through the entire codebase. (Counter-Example: EsMangle. You have 1 module per optimization step, not 1 with all of them)

My PR fixes this so the above workflow can be employed. The price is the exports (Hello proper CommonJS) and the imports/`var-stuff`. The gain is clean dependencies and even a speedup.

I do understand your point though. Maybe someone can figure out the cause of the slowdown which would help remove a lot of the redundancies.

Provocative conclusion: Why not use a single source file? Highest speed, no hacky paste&eval and no redundancies ;)

@goto-bus-stop I got that. But providing a browserified version (or a simple `npm run browserify-uglifyjs` step) makes it easier for people to use this at a very low cost.
I haven't tested the self-bundle because the benchmark relies on the bin/uglifyjs which does all the command line handling and then passes it to uglifyjs

**Comment by kzc** [comment]
> Why not use a single source file?

That may be the least worst option but then all future upstream bug fix merges would have to be done manually.

For the IDE debugging scenario, that's what `--self` already provides:

https://github.com/fabiosantoscode/terser/blob/fcf95d48c26d4b734e02cda3d96712e751b392c0/package.json#L41

which will be published in future releases.

Now that I look at the generated file `dist/browser.bundle.js`, it needs an extra IIFE parameter for `MOZ_SourceMap` so that the optional `source-map` library can be passed in.

As @goto-bus-stop mentioned, perhaps we could consider having a very thin wrapper over `dist/browser.bundle.js` to be the `main` entry point for the module. But that'd require a transpile phase `npm run prepublish` after any source change in the edit-test cycle. That might not be so terrible. Let me think about it.

**Comment by kzc** [comment]
Regardless of this IDE debugging issue, we should probably publish both an unminified and minified bundle with accompanying source map file:
```
dist/terser.bundle.js
dist/terser.bundle.min.js
dist/terser.bundle.min.js.map
```
These bundles could be used in either the browser or node.

**Comment by Flamefire** [comment]
For IDE debugging I consider it important to work directly on the source files:

- You can set Breakpoints directly (eval breaks this)
- You can change code directly once you found the buggy part (--self/transpile/... would break this)
