### ISSUE TITLE
Port harmony issue queue

### ISSUE THREAD

**Issue by guybedford** [fabiosantoscode/terser#4]
It may well make sense to repost all the harmony issues from https://github.com/mishoo/UglifyJS2/issues?q=is%3Aopen+is%3Aissue+label%3Aharmony to this repo. Hopefully this would even allow them to be closed at the UglifyJS2 project.

**Comment by toddself** [comment]
I would be willing to help with that -- it would give others a good task list of things to work on as well.

**Comment by guybedford** [comment]
@toddself please feel free to go ahead with this - perhaps with something like a "[uglify-es]" prefix or similar to make these easy to distinguish, although ideally we should have a new label for this.

**Comment by kzc** [comment]
Most open harmony bugs have already been fixed in `@fabiosantoscode/uglify-es`. Please verify that a given bug still exists before creating a ticket. Please follow this project's new issue template with an unambiguous succinct test case producing bad output once minified with certain options.

I wouldn't bother porting feature requests and non-bugs. Individuals can open such tickets in this project.

**Comment by toddself** [comment]
Thanks to the hard work from @kzc and @fabiosantoscode it looks like the only remaining bugs in the uglify-js that aren't marked as resolved in the threads are:

* https://github.com/mishoo/UglifyJS2/issues/2696
* https://github.com/mishoo/UglifyJS2/issues/2662
* https://github.com/mishoo/UglifyJS2/issues/1372

The first two seem to be low priority/edge cases.  The last one involves the test262 feature set. Are these even worth porting over?

**Comment by kzc** [comment]
No need for this ticket now that people are becoming more familiar with the Terser project.
