### ISSUE TITLE
Support folders or wildcards as input

### ISSUE THREAD

**Issue by kibertoad** [fabiosantoscode/terser#75]
**Feature request**

Considering that this is a fairly common usage scenario, it should be possible to provide a wildcard (src/**/*.js) or at the very least directory (src) as an input for the terser.
Libraries like https://github.com/ionutvmi/uglifyjs-folder exist, but this is an important use-case enough to belong in core functionality

**Comment by kzc** [comment]
We're trying to keep the focus squarely on minification and avoid feature creep. It's easy to provide that functionality in a wrapper. `glob` and its dependencies are larger than all of Terser.

**Comment by alexeagle** [comment]
that's reasonable @kzc - I need such a wrapper so I'm planning to write one. But do you know of any that already exist?

**Comment by alexeagle** [comment]
Trying to answer my own question:
- https://www.npmjs.com/package/terser-folder - the github repo for it no longer exists
- appears it was forked from https://github.com/ionutvmi/uglifyjs-folder
- neither of these has a LICENSE so lawyers say we can't use them

Anyway we want to use the new https://nodejs.org/api/worker_threads.html API to make it faster, now that Node 12 is about a month from LTS

So it seems that we do need to write a new one.

**Comment by kzc** [comment]
@alexeagle I no longer work on terser, but I can provide some background.

The terser API (and uglify-es and uglify-js@3 before it) do not support filesystem operations by design - it's all just synchronous in-memory operations. The `minify` call will also accept an array of code strings, or a map of name/code pairs. It is documented in the README and you can examine the typescript declaration file.

The CLI of these minifiers do have simple globbing support for files to feed the underlying `minify` API, but it's of limited use anyway since it just performs naive source concatenation. You need a bundler in most cases to do any useful work.

Making an async filesystem wrapper over `minify` is trivial and gives you more control over the process.

**Comment by alexeagle** [comment]
Thanks @kzc 
In addition to what I wrote above, we also found that having to re-implement the command-line parser of terser exposes us to too much maintenance burden and possibility of behaving differently than the underlying tool.
We ended up writing a simple wrapper that spawns the terser CLI in subprocesses.
https://github.com/bazelbuild/rules_nodejs/blob/master/packages/terser/src/index.js

If the community is interested, we could generalize this a tad (handle `--input` anywhere in the argv) and publish it as a standalone package not related to running under Bazel.
